name: app
description: A cross-platform todo tracker built with drift.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.4.1
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^1.7.0
  path_provider: ^2.0.9
  flutter_lorem: ^2.0.0
  executor: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  build: ^2.2.1
  drift_dev:

flutter:
  uses-material-design: true
